development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: physics_academy_test
  pool: 5
  username: ae
  password:
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: physics_academy_production
  pool: 5
  username: ae
  password:
  host: localhost
  port: 5432
  socket: /var/pgsql_socket
